import type { CanvasDimensionPreset, GraphicTemplate } from './types';

export const CANVAS_PRESETS: CanvasDimensionPreset[] = [
  { id: 'ig-square', name: 'Instagram Post (1:1)', width: 1080, height: 1080 },
  { id: 'ig-story', name: 'Story / Reel (9:16)', width: 1080, height: 1920 },
  { id: 'yt-thumb', name: 'YouTube Thumbnail (16:9)', width: 1280, height: 720 },
  { id: 'x-post', name: 'X / Twitter Post (16:9)', width: 1200, height: 675 },
  { id: 'fb-cover', name: 'Facebook Banner', width: 1200, height: 630 },
  { id: 'poster-a4', name: 'A4 Portrait Poster', width: 800, height: 1130 },
];

export const GRAPHIC_TEMPLATES: GraphicTemplate[] = [
  {
    id: 'template-social-launch',
    title: 'Product Launch 2026',
    category: 'social',
    width: 1080,
    height: 1080,
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    nodes: [
      {
        id: 'bg-card',
        kind: 'shape',
        name: 'Background Card',
        shapeType: 'rounded',
        x: 80,
        y: 80,
        width: 920,
        height: 920,
        backgroundColor: '#0f172a',
        borderRadius: 48,
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.4)',
      },
      {
        id: 'accent-pill',
        kind: 'shape',
        name: 'Category Pill',
        shapeType: 'pill',
        x: 160,
        y: 160,
        width: 240,
        height: 56,
        backgroundColor: '#7c3aed',
        borderRadius: 28,
      },
      {
        id: 'pill-text',
        kind: 'text',
        name: 'Badge Label',
        text: '⚡ NEW RELEASE',
        x: 160,
        y: 172,
        width: 240,
        height: 32,
        fontSize: 16,
        fontWeight: '800',
        color: '#ffffff',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
        textAlign: 'center',
      },
      {
        id: 'main-title',
        kind: 'text',
        name: 'Main Title',
        text: 'DESIGN AT THE SPEED OF LIGHT',
        x: 160,
        y: 260,
        width: 760,
        height: 200,
        fontSize: 64,
        fontWeight: '900',
        color: '#ffffff',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
        lineHeight: 1.1,
      },
      {
        id: 'subtitle',
        kind: 'text',
        name: 'Subtitle',
        text: 'Build modern graphics, multi-track videos, and schedule social media with unified Google Gemini AI.',
        x: 160,
        y: 480,
        width: 760,
        height: 80,
        fontSize: 22,
        fontWeight: '500',
        color: '#94a3b8',
        fontFamily: 'Inter, sans-serif',
        lineHeight: 1.5,
      },
      {
        id: 'hero-image',
        kind: 'image',
        name: 'Product Mockup',
        src: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        x: 160,
        y: 590,
        width: 760,
        height: 330,
        borderRadius: 24,
        boxShadow: '0 20px 40px rgba(0, 0, 0, 0.3)',
      },
    ],
  },
  {
    id: 'template-yt-thumb',
    title: 'YouTube Viral Thumbnail',
    category: 'marketing',
    width: 1280,
    height: 720,
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&auto=format&fit=crop&q=80',
    nodes: [
      {
        id: 'bg-grad',
        kind: 'shape',
        name: 'Canvas Backdrop',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        backgroundColor: '#09090b',
      },
      {
        id: 'img-featured',
        kind: 'image',
        name: 'Creator Focus',
        src: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
        x: 680,
        y: 60,
        width: 540,
        height: 600,
        borderRadius: 32,
      },
      {
        id: 'yt-headline',
        kind: 'text',
        name: 'Bold Hook',
        text: 'CANVA IS OVER.',
        x: 80,
        y: 120,
        width: 580,
        height: 160,
        fontSize: 72,
        fontWeight: '900',
        color: '#fbbf24',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
        lineHeight: 1.05,
      },
      {
        id: 'yt-badge',
        kind: 'shape',
        name: 'Highlight Badge',
        shapeType: 'pill',
        x: 80,
        y: 310,
        width: 380,
        height: 64,
        backgroundColor: '#ef4444',
        borderRadius: 32,
      },
      {
        id: 'yt-badge-text',
        kind: 'text',
        name: 'Badge Text',
        text: '100% OPEN SOURCE',
        x: 80,
        y: 324,
        width: 380,
        height: 36,
        fontSize: 22,
        fontWeight: '900',
        color: '#ffffff',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
        textAlign: 'center',
      },
      {
        id: 'yt-sub',
        kind: 'text',
        name: 'Sub text',
        text: 'Google Gemini 3 Flash & Veo Video Studio',
        x: 80,
        y: 420,
        width: 540,
        height: 60,
        fontSize: 24,
        fontWeight: '600',
        color: '#f4f4f5',
        fontFamily: 'Inter, sans-serif',
      },
    ],
  },
  {
    id: 'template-cyber-banner',
    title: 'Cyberpunk Tech Drop',
    category: 'social',
    width: 1200,
    height: 675,
    nodes: [
      {
        id: 'bg-dark',
        kind: 'shape',
        name: 'Cyber Base',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 1200,
        height: 675,
        backgroundColor: '#030712',
      },
      {
        id: 'neon-box-1',
        kind: 'shape',
        name: 'Neon Glow Box',
        shapeType: 'rounded',
        x: 80,
        y: 60,
        width: 1040,
        height: 555,
        backgroundColor: '#111827',
        borderColor: '#7c3aed',
        borderWidth: 3,
        borderRadius: 24,
        boxShadow: '0 0 50px rgba(124, 58, 237, 0.4)',
      },
      {
        id: 'cyber-title',
        kind: 'text',
        name: 'Cyber Title',
        text: 'REZIT STUDIO 2.0',
        x: 140,
        y: 140,
        width: 920,
        height: 90,
        fontSize: 64,
        fontWeight: '900',
        color: '#00c4cc',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
        textAlign: 'center',
      },
      {
        id: 'cyber-tag',
        kind: 'text',
        name: 'Cyber Subtitle',
        text: 'THE AI-NATIVE CREATIVE WORKSPACE',
        x: 140,
        y: 240,
        width: 920,
        height: 40,
        fontSize: 20,
        fontWeight: '700',
        color: '#ec4899',
        fontFamily: 'JetBrains Mono, monospace',
        textAlign: 'center',
        letterSpacing: 4,
      },
      {
        id: 'cyber-btn',
        kind: 'shape',
        name: 'Action Button',
        shapeType: 'pill',
        x: 460,
        y: 350,
        width: 280,
        height: 64,
        backgroundColor: '#7c3aed',
        borderRadius: 32,
      },
      {
        id: 'cyber-btn-txt',
        kind: 'text',
        name: 'Button Label',
        text: 'GET STARTED →',
        x: 460,
        y: 366,
        width: 280,
        height: 32,
        fontSize: 18,
        fontWeight: '800',
        color: '#ffffff',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'template-quote-minimal',
    title: 'Minimalist Editorial Card',
    category: 'poster',
    width: 1080,
    height: 1080,
    nodes: [
      {
        id: 'bg-cream',
        kind: 'shape',
        name: 'Canvas Frame',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        backgroundColor: '#f8fafc',
      },
      {
        id: 'inner-card',
        kind: 'shape',
        name: 'Inner White Card',
        shapeType: 'rounded',
        x: 90,
        y: 90,
        width: 900,
        height: 900,
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
        borderWidth: 2,
        borderRadius: 32,
        boxShadow: '0 20px 40px rgba(0, 0, 0, 0.04)',
      },
      {
        id: 'quote-mark',
        kind: 'text',
        name: 'Quote Mark',
        text: '“',
        x: 160,
        y: 180,
        width: 120,
        height: 100,
        fontSize: 140,
        fontWeight: '900',
        color: '#7c3aed',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
      },
      {
        id: 'quote-body',
        kind: 'text',
        name: 'Quote Statement',
        text: 'Simplicity is about subtracting the obvious and adding the meaningful.',
        x: 160,
        y: 340,
        width: 760,
        height: 260,
        fontSize: 48,
        fontWeight: '700',
        color: '#0f172a',
        fontFamily: 'Plus Jakarta Sans, sans-serif',
        lineHeight: 1.25,
      },
      {
        id: 'quote-author',
        kind: 'text',
        name: 'Author Citation',
        text: '— JOHN MAEDA, THE LAWS OF SIMPLICITY',
        x: 160,
        y: 640,
        width: 760,
        height: 40,
        fontSize: 16,
        fontWeight: '700',
        color: '#64748b',
        fontFamily: 'Inter, sans-serif',
        letterSpacing: 2,
      },
    ],
  },
];
